"""Benchmark task registry for OpenEnv validator compatibility."""

TASKS = [
    {
        "id": "companiesim_growth_001",
        "task_id": "companiesim_growth_001",
        "title": "Revenue Growth Sprint",
        "difficulty": "easy",
        "description": "Maximize revenue and user growth while avoiding bankruptcy.",
        "objective": "Increase revenue and active users over the episode while keeping capital non-negative.",
        "success_criteria": "Revenue growth >= 0.18, user growth >= 0.12, and capital remains non-negative.",
        "score_range": {"min": 0.0, "max": 1.0},
        "grader": {
            "name": "revenue_growth",
            "metric": "revenue_growth_pct",
            "weight": 0.5,
            "direction": "maximize",
            "threshold": 0.18,
            "deterministic": True,
            "score_min": 0.0,
            "score_max": 1.0,
        },
        "graders": [
            {
                "name": "revenue_growth",
                "metric": "revenue_growth_pct",
                "weight": 0.5,
                "direction": "maximize",
                "threshold": 0.18,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "user_growth",
                "metric": "active_user_growth_pct",
                "weight": 0.3,
                "direction": "maximize",
                "threshold": 0.12,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "capital_safety",
                "metric": "capital_non_negative",
                "weight": 0.2,
                "direction": "maximize",
                "threshold": 1.0,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
        ],
    },
    {
        "id": "companiesim_efficiency_002",
        "task_id": "companiesim_efficiency_002",
        "title": "Cost Efficiency Run",
        "difficulty": "medium",
        "description": "Reduce operational cost while maintaining satisfaction and quality.",
        "objective": "Reduce operational costs without dropping customer satisfaction and product quality below safe floors.",
        "success_criteria": "Cost reduction >= 0.10, satisfaction >= 0.45, and quality >= 0.45 (all normalized to 0..1 scores).",
        "score_range": {"min": 0.0, "max": 1.0},
        "grader": {
            "name": "cost_reduction",
            "metric": "operational_cost_reduction_pct",
            "weight": 0.45,
            "direction": "maximize",
            "threshold": 0.1,
            "deterministic": True,
            "score_min": 0.0,
            "score_max": 1.0,
        },
        "graders": [
            {
                "name": "cost_reduction",
                "metric": "operational_cost_reduction_pct",
                "weight": 0.45,
                "direction": "maximize",
                "threshold": 0.1,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "satisfaction_floor",
                "metric": "min_customer_satisfaction",
                "weight": 0.35,
                "direction": "maximize",
                "threshold": 45.0,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "quality_floor",
                "metric": "min_product_quality",
                "weight": 0.2,
                "direction": "maximize",
                "threshold": 45.0,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
        ],
    },
    {
        "id": "companiesim_balanced_003",
        "task_id": "companiesim_balanced_003",
        "title": "Balanced Strategy Challenge",
        "difficulty": "hard",
        "description": "Balance growth, retention, and risk under uncertainty.",
        "objective": "Maintain balanced long-horizon performance with strong reward, retention, and bankruptcy avoidance.",
        "success_criteria": "Normalized reward >= 0.55, retained users >= 0.30, and bankruptcy avoided.",
        "score_range": {"min": 0.0, "max": 1.0},
        "grader": {
            "name": "normalized_reward",
            "metric": "episode_normalized_reward",
            "weight": 0.4,
            "direction": "maximize",
            "threshold": 0.55,
            "deterministic": True,
            "score_min": 0.0,
            "score_max": 1.0,
        },
        "graders": [
            {
                "name": "normalized_reward",
                "metric": "episode_normalized_reward",
                "weight": 0.4,
                "direction": "maximize",
                "threshold": 0.55,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "retention_proxy",
                "metric": "retained_user_ratio",
                "weight": 0.3,
                "direction": "maximize",
                "threshold": 0.3,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
            {
                "name": "bankruptcy_avoidance",
                "metric": "bankruptcy_avoidance",
                "weight": 0.3,
                "direction": "maximize",
                "threshold": 1.0,
                "deterministic": True,
                "score_min": 0.0,
                "score_max": 1.0,
            },
        ],
    },
]


def get_tasks():
    return TASKS
